version: 2

project_name: supasecure

before:
  hooks:
    - go mod tidy

builds:
  - id: supasecure
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

archives:
  - formats: [ tar.gz ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ zip ]

release:
  github:
    owner: train360-corp
    name: supasecure

  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

brews:
  - name: supasecure
    url_template: "https://github.com/train360-corp/homebrew-tap/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    url_headers:
      - "Accept: application/octet-stream"
      - 'Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}'
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "feat: brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    caveats: "supasecure --help"
    homepage: "https://github.com/train360-corp/homebrew-tap"
    description: "CLI for interacting with a Supasecure instance."
    license: "MIT"

    # Packages your package depends on.
#    dependencies:
#      - name: git
#        # Allow to specify the OS in which the dependency is required.
#        # Valid options are `mac` and `linux`.
#        os: mac
#      - name: zsh
#        type: optional
#      - name: fish
#        version: v1.2.3
#      # if providing both version and type, only the type will be taken into
#      # account.
#      - name: elvish
#        type: optional
#        version: v1.2.3
    test: |
      system "#{bin}/supasecure --version"
      # ...

    repository:
      owner: train360-corp
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"