name: release

on:
  push:
    tags:
      - "v*.*.*"  # Matches v1.0.0, v2.3.4, etc.

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
          workdir: './cli'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_REPO_SECRET: ${{ secrets.HOMEBREW_TAP_REPO_SECRET }}

  types:
    needs:
      - goreleaser
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@v4

      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq moreutils

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase db start

      - name: update package.json version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          jq --arg VERSION "$VERSION" '.version = $VERSION' package.json | sponge package.json

      - run: npm i

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_KEY }}
